// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Name = {__proto__:null,default:10, _:16, ERASE:16, BLANK:16, "*":16, ELSE:16, SAME:16, HALT:48, halt:50}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$nQVQPOOOeQPO'#CgOsQPO'#CfOOQO'#Cn'#CnOsQPO'#CmOOQO'#Cz'#CzOOQO'#Cv'#CvQVQPOOOsQPO'#C_O!OQQO,59ROOQO'#Cc'#CcOOQO'#Cb'#CbOOQO,59Q,59QOOQO'#Co'#CoOsQPO,59XOOQO-E6t-E6tOOQO,58y,58yO!TQPO1G.mOOQO'#Cp'#CpO!YQPO1G.sO!_QQO7+$XOOQO'#Cq'#CqO!dQPO7+$_O!oQPO<<GsOOQO'#Cs'#CsOOQO'#Cr'#CrOOQO<<Gy<<GyOOQOAN=_AN=_",
  stateData: "!y~OmOS~OQTOSROTWO[PO~O]XOSZXWZXXZX~OSZOWYOXZO~O^aO~O_dO~OSeO~O^gO~OSiOhhOihO~O`kO~OQ[S[~",
  goto: "!yoPPPpPPt!QPPp!WPPPPPp![!`!c!f!i!lPP!oPPP!uTTOVQ[QQ]SQ`WRb^XZQSW^TQOVTSOVR^SRc^RfcRjfRifQVOR_VTUOV",
  nodeNames: "⚠ Program LineComment DefaultDirective Name DirectiveKeyword Symbol SpecialSymbolKw SpecialSymbol QuotedString InputDirective InputKeyword DirectiveKeyword [ Number , ] Transition CurrentState ReadSymbol WriteSymbol MoveDir NextState HaltKw Halt Halt",
  maxTerm: 30,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "/k~RkXY!vYZ!v]^!vpq!vqr#Xrs$`st#Xvw#Xz{#X{|#X|}%|}!O&R!O!P#X!P!Q(c!Q!['Y!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X!}#O)Q#P#Q)V#Q#R#X#R#S#X#T#]#X#]#^)[#^#o#X~!{Sm~XY!vYZ!v]^!vpq!vP#^`SPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q![#X!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#o#X~$cVOr$`rs$xs#O$`#O#P$}#P;'S$`;'S;=`%v<%lO$`~$}OX~~%QRO;'S$`;'S;=`%Z;=`O$`~%^WOr$`rs$xs#O$`#O#P$}#P;'S$`;'S;=`%v;=`<%l$`<%lO$`~%yP;=`<%l$`~&RO_~R&W`SPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q!['Y!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#o#XR'a`^QSPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q!['Y!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#o#X~(fP!P!Q(i~(nSQ~OY(iZ;'S(i;'S;=`(z<%lO(i~(}P;=`<%l(i~)VO]~~)[O`~~)abSPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q![#X!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#b#X#b#c*i#c#o#X~*nbSPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q![#X!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#d#X#d#e+v#e#o#X~+{bSPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q![#X!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#i#X#i#j-T#j#o#X~-YbSPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q![#X!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#h#X#h#i.b#i#o#X~.i`[~SPqr#Xst#Xvw#Xz{#X{|#X}!O#X!O!P#X!Q![#X!^!_#X!_!`#X!`!a#X!b!c#X!c!}#X#Q#R#X#R#S#X#T#o#X",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  specialized: [{term: 4, get: (value) => spec_Name[value] || -1}],
  tokenPrec: 82
})
